title = "Paper-Siege-Docs"  # From Git
gitRepoUrl = "https://github.com/Neverlife-Studios/Paper-Siege-Docs" # From Git

gitSourceBranch = "master"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

# From git:
organizationName = "Neverlife Studios"
projectName = "Paper-Siege-Docs"
url = "https://Neverlife-Studios.github.io"
baseUrl = "/Paper-Siege-Docs"
tagline = "Documentation for the game Paper Siege"

[footer]
style = "dark"
copyright = "Copyright © 2023 Neverlife Studios. Built with Moonwave and Docusaurus"